### ISSUE TITLE
Track down which file is still requesting old common.html

### ISSUE THREAD

**Issue by stardust66** [stardust66/math3d#1]
After changing app structure for Flask, both the vendors and resources folders are in `/static/`. I've changed all the references I could find accordingly. However, there is still a file that's requesting `/resources/templates/common.html` and I couldn't find where it was. The temporary solution is in `app.py` (manually redirecting):

```
@app.route('/resources/templates/common.html')
def record():
    return redirect("/static/resources/templates/common.html")
```

**Comment by ChristopherChudzicki** [comment]
How can I reproduce the error you're finding?

I managed to run this branch locally (I'm probably not running locally in the best way. I added a run.py file and had to comment out the lines in `app.py` with `SECRET_KEY` and `SQLALCHEMY_DATABASE_URI`, but they seemed not to do anything yet).

After commenting out 
```
@app.route('/resources/templates/common.html')
def record():
    return redirect("/static/resources/templates/common.html")
```
everything seems to run fine. I tried adding all the object types, I didn't see any denied requests.

**Comment by stardust66** [comment]
Hmm. I'm running it with `Flask run`. Had to first set `export FLASK_APP=app.py`. I just ran this and the error in the javascript console stopped happening, but there's a line in the output of `Flask run`:
```
127.0.0.1 - - [26/Apr/2017 17:21:16] "GET /resources/templates/common.html HTTP/1.1" 304
```
which means something's still trying to access the old url and the server's returning an error, but it doesn't seem to affect the anything.

**Comment by stardust66** [comment]
I think it's safe to take that line out for now.
